### ISSUE TITLE
.exe on dist being flagged by some antivirus vendors are malware

### ISSUE THREAD

**Issue by vico93** [BirnB4um/MC_Skin_Generator#1]
From [VirusTotal](https://www.virustotal.com/gui/file/1fde4a42b0058d97c087c4634dc2e730842857466605b3d9209a7aa80c8b62d8?nocache=1).

Both Fortinet and Ikarus flag the .exe on `dist` as a threat.

**Comment by BirnB4um** [comment]
Hi vico93, I believe there are always some antivirus programs that flag it as a threat. So I'm not quite sure what to do about it. Alternatively you can run *app.py* manually if you don't trust the .exe.
